### ISSUE TITLE
Doxygen Latex missing

### ISSUE THREAD

**Issue by jolau** [ANYbotics/kindr#116]
On https://docs.leggedrobotics.com/kindr/index.html the images of the latex formulas are missing and therefore only shows the (incomprehensible) latex code. Could you please fix it? Otherwise the docs are not really usable.

**Comment by remod** [comment]
Thanks for reporting this. @pleemann Is `texlive-latex-base` installed on the build server? It is required to compile the latex formulas in doxygen.

**Comment by pleemann** [comment]
No its not, but adding it as <code_depend> should do the trick

**Comment by pleemann** [comment]
No its not, but adding it as <code_depend> should do the trick

**Comment by remod** [comment]
Do you mean <doc_depend>?

**Comment by pleemann** [comment]
Yes, sorry

**Comment by remod** [comment]
It does not seem to have solved the issue, any ideas?

**Comment by jolau** [comment]
Maybe you could also try to use MathJax instead, by enable USE_MATHJAX: http://www.doxygen.nl/manual/config.html#cfg_use_mathjax

**Comment by pleemann** [comment]
It should work, but the docs on https://docs.leggedrobotics.com/kindr/index.html are not automatically updated anymore. The documentation with proper latex formulas will be available under new URL after next release (latest end of this month). Stay tuned and sorry for any inconvenience.

**Comment by hogabrie** [comment]
I updated the README with the new URL.  See 0c16c8232d5404b09284cb6a441365172e163b2b
