### ISSUE TITLE
Doxygen Link in Readme (404)

### ISSUE THREAD

**Issue by Claudio-Chies** [ANYbotics/kindr#124]
The Doxygen link in the readme links to a 404 page.
It currently points _https://github.com/ANYbotics/kindr/blob/master/www.doxygen.org_ instead of _www.doxygen.org_
minor detail, but I thought I'd mention it.

Line 119 should probably be:
` Build the documentation with [Doxygen](https://www.doxygen.org):`

**Comment by remod** [comment]
Fixed with https://github.com/ANYbotics/kindr/commit/bc30122726518fbf34b19d5c33d63f45d18f2c1c, thanks for letting us know.
